"""Convert source-tex/*.tex to lectures/*.qmd.

Pipeline per file:
  1. Pre-pass:  drop checkpoints, swap color blocks for callouts, replace
                tikz with image refs, strip per-lecture LaTeX bookkeeping,
                extract part title.
  2. Pandoc:    LaTeX -> Markdown with --katex math passthrough.
  3. Post-pass: minor cleanup of pandoc artifacts.
  4. YAML wrap.

Idempotent: overwrites lectures/lec0N.qmd on every run.
"""
from __future__ import annotations
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "source-tex"
OUT = ROOT / "lectures"

BLOCK_MAP = {
    "keyblock":      ("important", "Key concept"),
    "exerciseblock": ("caution",   "Exercise"),
    "noteblock":     ("note",      "Note"),
    "tipblock":      ("tip",       "Filling the gap"),
}

# Unicode sentinels survive pandoc as plain text. Post-pass swaps them
# for proper Quarto fenced-div syntax.
SENTINEL_OPEN = {
    "keyblock":      "§§KEYBLOCK_OPEN§§",
    "exerciseblock": "§§EXERCISEBLOCK_OPEN§§",
    "noteblock":     "§§NOTEBLOCK_OPEN§§",
    "tipblock":      "§§TIPBLOCK_OPEN§§",
}
SENTINEL_CLOSE = "§§BLOCK_CLOSE§§"

CHECKPOINT_RE = re.compile(
    r"\\begin\{checkpoint\}.*?\\end\{checkpoint\}", re.DOTALL
)
TIKZ_RE = re.compile(
    r"\\begin\{tikzpicture\}.*?\\end\{tikzpicture\}", re.DOTALL
)
PART_RE = re.compile(r"\\part\*\{Lecture\s+(\d+):\s*([^}]+)\}")


def remove_checkpoint_blocks(tex: str) -> str:
    return CHECKPOINT_RE.sub("", tex)


def convert_color_blocks(tex: str) -> str:
    """Pre-pass: swap mdframed envs for unicode sentinels.

    The sentinels survive pandoc untouched; restore_callout_sentinels
    converts them back to Quarto fenced-div syntax in the markdown output.
    """
    for env in BLOCK_MAP:
        tex = re.sub(
            rf"\\begin\{{{env}\}}",
            f"\n\n{SENTINEL_OPEN[env]}\n\n",
            tex,
        )
        tex = re.sub(
            rf"\\end\{{{env}\}}",
            f"\n\n{SENTINEL_CLOSE}\n\n",
            tex,
        )
    return tex


def restore_callout_sentinels(md: str) -> str:
    """Post-pass: replace sentinels with Quarto fenced-div callout syntax."""
    for env, (callout, title) in BLOCK_MAP.items():
        md = md.replace(
            SENTINEL_OPEN[env],
            f':::{{.callout-{callout} title="{title}"}}',
        )
    md = md.replace(SENTINEL_CLOSE, ":::")
    return md


def replace_tikz_blocks(tex: str, lecture_num: int) -> tuple[str, int]:
    counter = {"i": 0}

    def sub(_m):
        counter["i"] += 1
        # Use \includegraphics so pandoc converts it to proper markdown image.
        return (
            f"\\includegraphics{{../figures/L{lecture_num}_tikz_{counter['i']}.png}}"
        )

    return TIKZ_RE.sub(sub, tex), counter["i"]


def strip_lecture_macros(tex: str) -> str:
    tex = re.sub(r"\\beginlecture\{\d+\}", "", tex)
    tex = re.sub(r"\\addcontentsline\{toc\}\{part\}\{[^}]*\}", "", tex)
    tex = tex.replace("\\textperiodcentered{}", "·")
    return tex


def extract_part_title(tex: str) -> tuple[int, str]:
    m = PART_RE.search(tex)
    if not m:
        raise ValueError("no \\part*{Lecture N: ...} found")
    return int(m.group(1)), m.group(2).strip()


def strip_part(tex: str) -> str:
    return PART_RE.sub("", tex)


def run_pandoc(tex: str) -> str:
    proc = subprocess.run(
        ["pandoc", "-f", "latex", "-t", "markdown",
         "--wrap=preserve", "--katex"],
        input=tex,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    return proc.stdout


def clean_pandoc_output(md: str) -> str:
    # Pandoc may escape underscores in image paths in markdown output
    md = re.sub(
        r"!\[([^\]]*)\]\(((?:\.\./)?figures/[^)]+)\)",
        lambda m: f"![{m.group(1)}](" + m.group(2).replace("\\_", "_") + ")",
        md,
    )
    # Rewrite root-relative figure paths to be relative to lectures/
    md = re.sub(
        r"(!\[[^\]]*\]\()figures/",
        r"\1../figures/",
        md,
    )
    return md


def wrap_with_yaml(md: str, title: str, lecture_num: int) -> str:
    header = (
        "---\n"
        f'title: "Lecture {lecture_num}: {title}"\n'
        "number-sections: true\n"
        "---\n\n"
        "<!-- AUTO-GENERATED by scripts/convert.py — do not edit. -->\n\n"
    )
    return header + md


def convert_file(tex_path: Path) -> None:
    raw = tex_path.read_text(encoding="utf-8")
    lecture_num, title = extract_part_title(raw)
    tex = strip_part(raw)
    tex = remove_checkpoint_blocks(tex)
    tex = convert_color_blocks(tex)
    tex, tikz_n = replace_tikz_blocks(tex, lecture_num)
    tex = strip_lecture_macros(tex)
    md = run_pandoc(tex)
    md = restore_callout_sentinels(md)
    md = clean_pandoc_output(md)
    md = wrap_with_yaml(md, title, lecture_num)
    out = OUT / f"lec{lecture_num:02d}.qmd"
    out.write_text(md, encoding="utf-8")
    print(f"  {tex_path.name} -> {out.name} ({tikz_n} tikz)")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    sources = sorted(SRC.glob("lec*.tex"))
    if not sources:
        print("no source .tex files in source-tex/", file=sys.stderr)
        sys.exit(1)
    for tex in sources:
        convert_file(tex)
    print(f"done: {len(sources)} lectures")


if __name__ == "__main__":
    main()
